require("libraries/webapi/declarations")
require("libraries/webapi/item_definitions/init")
require("libraries/webapi/error_tracking")
require("libraries/webapi/inventory/inventory")
require("libraries/webapi/player")
require("libraries/webapi/settings")
require("libraries/webapi/tips")
require("libraries/webapi/cosmetic_abilities/cosmetic_abilities")
