assert(IsInToolsMode() and HeroSwaps:IsOpen())
GameRules:ForceGameStart()
Timers:CreateTimer(1, function()
	assert(GameRules:State_Get() >= DOTA_GAMERULES_STATE_GAME_IN_PROGRESS)
	assert(not HeroSwaps:IsOpen())
	assert(CustomNetTables:GetTableValue("game_options", "hero_swaps").open == 0)
	assert(not HeroSwaps:Handle("request", 0, {target=1}))
	print("HERO_SWAPS_CLOSE_PASS server rejects swaps and closes UI at match start")
end)
