CHAT_WHEEL_RINGS = {
	default = {
		"local_hero",
		"commentators_1",
		"favorites",
		"",
		"misc_1",
		"battle_pass_1",
		"dota_plus_2",
		"dota_plus_1"
	},
	misc_1 = {
		{ "dota_chatwheel_message_Celebratory_Gong", "soundboard.new_year_gong" },
		{ "dota_chatwheel_message_Sleighbells", "soundboard.sleighbells" },
		{ "dota_chatwheel_message_Oink_Oink", "soundboard.new_year_pig" },
		{ "dota_chatwheel_message_Greevil_Laughter", "soundboard.greevil_laughs" },
		{ "dota_chatwheel_message_Frostivus_Magic", "soundboard.frostivus_magic" },
		{ "dota_chatwheel_message_Ceremonial_Drums", "soundboard.new_year_drums" },
		"",
		""
	},
	battle_pass_1 = {
		{ "kooka_laugh", "custom_soundboard.ti9_kooka_laugh" },
		{ "monkey_biz", "custom_soundboard.ti9_monkey_biz" },
		{ "orangutan_kiss", "custom_soundboard.ti9_orangutan_kiss" },
		{ "skeeter", "custom_soundboard.ti9_skeeter" },
		{ "crowd_groan", "custom_soundboard.ti9_crowd_groan" },
		{ "head_bonk", "custom_soundboard.ti9_head_bonk" },
		{ "record_scratch", "custom_soundboard.ti9_record_scratch" },
		{ "ta_da", "custom_soundboard.ti9_ta_da" },
	},
	dota_plus_1 = {
		{ "dota_chatwheel_label_Headshake", "soundboard.headshake" },
		{ "dota_chatwheel_label_Kiss", "soundboard.kiss" },
		{ "dota_chatwheel_label_Ow", "soundboard.ow" },
		{ "dota_chatwheel_label_Snore", "soundboard.snore" },
		{ "dota_chatwheel_label_Bockbock", "soundboard.bockbock" },
		{ "dota_chatwheel_label_Crybaby", "soundboard.crybaby" },
		{ "dota_chatwheel_label_Sad_Trombone", "soundboard.sad_bone" },
		{ "dota_chatwheel_label_Yahoo", "soundboard.yahoo" },
	},
	dota_plus_2 = {
		{ "dota_chatwheel_label_Applause", "soundboard.applause" },
		{ "dota_chatwheel_label_Crash_and_Burn", "soundboard.crash" },
		{ "dota_chatwheel_label_Crickets", "soundboard.cricket" },
		{ "dota_chatwheel_label_Party_Horn", "soundboard.party_horn" },
		{ "dota_chatwheel_label_Rimshot", "soundboard.rimshot" },
		{ "dota_chatwheel_label_Charge", "soundboard.charge" },
		{ "dota_chatwheel_label_Drum_Roll", "soundboard.drum_roll" },
		{ "dota_chatwheel_label_Frog", "soundboard.frog" },
	},
	commentators_1 = {
		"english_commentators_1",
		"chinese_commentators_1",
		"russian_commentators_1",
		"",
		"",
		"",
		"epic_casters_1",
		"korean_commentators_1"
	},
	epic_casters_1 = {
		"epic_casters_2",
		{ "easiest_money", "soundboard.easiest_money" },
		{ "echo_slama_jama", "soundboard.echo_slama_jama" },
		{ "next_level", "soundboard.next_level" },
		"",
		{ "ta_daaaa", "soundboard.ta_daaaa" },
		{ "goodness_gracious", "soundboard.goodness_gracious" },
		{ "oy_oy_oy", "soundboard.oy_oy_oy" },
	},
	epic_casters_2 = {
		{ "nakupuuu", "soundboard.nakupuuu" },
		{ "whats_cooking", "soundboard.whats_cooking" },
		{ "eughahaha", "soundboard.eughahaha" },
		{ "glados_chat_21", "custom_soundboard.glados_chat_01" },
		{ "glados_chat_01", "custom_soundboard.glados_chat_21" },
		{ "glados_chat_07", "custom_soundboard.glados_chat_04" },
		{ "glados_chat_04", "custom_soundboard.glados_chat_07" },
		""
	},
	english_commentators_1 = {
		"english_commentators_2",
		{ "patience", "soundboard.patience" },
		{ "wow", "soundboard.wow" },
		{ "all_dead", "soundboard.all_dead" },
		{ "brutal", "soundboard.brutal" },
		"", -- { "disastah", "soundboard.disastah" }, no valid sound
		"", -- { "oh_my_lord", "soundboard.oh_my_lord" }, no valid sound
		{ "youre_a_hero", "soundboard.youre_a_hero" },
	},
	english_commentators_2 = {
		{ "that_was_questionable", "soundboard.that_was_questionable" },
		{ "playing_to_win", "soundboard.playing_to_win" },
		{ "what_just_happened", "soundboard.what_just_happened" },
		{ "looking_spicy", "soundboard.looking_spicy" },
		{ "no_chill", "soundboard.no_chill" },
		{ "ding_ding_ding", "custom_soundboard.ding_ding_ding" },
		{ "absolutely_perfect", "soundboard.absolutely_perfect" },
		{ "lets_play", "custom_soundboard.lets_play" },
	},
	chinese_commentators_1 = {
		"chinese_commentators_2",
		{ "duiyou_ne", "soundboard.duiyou_ne" },
		{ "wan_bu_liao_la", "soundboard.wan_bu_liao_la" },
		{ "po_liang_lu", "soundboard.po_liang_lu" },
		{ "tian_huo", "soundboard.tian_huo" },
		{ "jia_you", "soundboard.jia_you" },
		{ "zou_hao_bu_song", "soundboard.zou_hao_bu_song" },
		{ "liu_liu_liu", "soundboard.liu_liu_liu" },
	},
	chinese_commentators_2 = {
		{ "hu_lu_wa", "soundboard.hu_lu_wa" },
		{ "ni_qi_bu_qi", "soundboard.ni_qi_bu_qi" },
		{ "gao_fu_shuai", "soundboard.gao_fu_shuai" },
		{ "gan_ma_ne_xiong_di", "soundboard.gan_ma_ne_xiong_di" },
		{ "bai_tuo_shei_qu", "soundboard.bai_tuo_shei_qu" },
		{ "piao_liang", "soundboard.piao_liang" },
		{ "lian_dou_xiu_wai_la", "soundboard.lian_dou_xiu_wai_la" },
		{ "zai_jian_le_bao_bei", "soundboard.zai_jian_le_bao_bei" },
	},
	russian_commentators_1 = {
		"russian_commentators_2",
		{ "bozhe_ti_posmotri", "soundboard.bozhe_ti_posmotri" },
		{ "zhil_do_konsta", "soundboard.zhil_do_konsta" },
		{ "ay_ay_ay", "soundboard.ay_ay_ay" },
		{ "ehto_g_g", "soundboard.ehto_g_g" },
		{ "eto_prosto_netchto", "soundboard.eto_prosto_netchto" },
		{ "krasavchik", "soundboard.krasavchik" },
		{ "bozhe_kak_eto_bolno", "soundboard.bozhe_kak_eto_bolno" },
	},
	russian_commentators_2 = {
		{ "oy_oy_bezhat", "soundboard.oy_oy_bezhat" },
		{ "eto_nenormalno", "soundboard.eto_nenormalno" },
		{ "eto_sochno", "soundboard.eto_sochno" },
		{ "kreasa_kreasa", "soundboard.kreasa_kreasa" },
		{ "kak_boyge_te_byechenya", "soundboard.kak_boyge_te_byechenya" },
		{ "eto_ge_popayx_feeda", "soundboard.eto_ge_popayx_feeda" },
		{ "da_da_da_nyet", "soundboard.da_da_da_nyet" },
		{ "wot_eto_bru", "soundboard.wot_eto_bru" },
	},
	korean_commentators_1 = {
		{ "kor_yes_no", "custom_soundboard.kor_yes_no" },
		{ "kor_scan", "custom_soundboard.kor_scan" },
		{ "kor_immortality", "custom_soundboard.kor_immortality" },
		{ "kor_roshan", "custom_soundboard.kor_roshan" },
		{ "kor_yolo", "custom_soundboard.kor_yolo" },
		{ "kor_million_dollar_house", "custom_soundboard.kor_million_dollar_house" },
		"",
		""
	},
}