require("libraries/webapi/item_definitions/kill_effects")
require("libraries/webapi/item_definitions/auras")
require("libraries/webapi/item_definitions/pets")
require("libraries/webapi/item_definitions/hero_effects")
require("libraries/webapi/item_definitions/sprays")
require("libraries/webapi/item_definitions/cosmetic_skills")
require("libraries/webapi/item_definitions/high_fives")
